- view: et_send_jobs
  sql_table_name: exacttarget.main.et_send_jobs
  fields:

#-- fk

  - dimension: client_id
    type: number
    sql: ${TABLE}.client_id
    hidden: true

  - dimension: send_id
    label: 'Send ID'
    type: number
    sql: ${TABLE}.send_id
    hidden: false

#-- dimensions

  - dimension: from_name
    label: 'From Name'
    type: string
    sql: ${TABLE}.from_name
    
  - dimension: from_email
    label: 'From Email Adrs'
    type: string
    sql: ${TABLE}.from_email
    
  - dimension: email_name
    label: 'Email Name'
    type: string
    sql: ${TABLE}.email_name
    
  - dimension: subject
    label: 'Subject Line'
    type: string
    sql: ${TABLE}.subject
    
  - dimension: subject_line_len
    label: 'Subject Line Length'
    type: number
    sql: length( ${TABLE}.subject )
    
  - dimension: sent_time
    label: 'Sent Date'
    type: time
    timeframes: [hour_of_day, day_of_week, date]
    sql: ${TABLE}.sent_time
    hidden: true
    
  - dimension: email_type
    label: 'Email Type'
    type: string
    drill_fields: [email_name]
    sql: |
      CASE
            WHEN lower( ${TABLE}.email_name ) LIKE ('%welcome%') THEN 'Welcome Email'
            WHEN ${TABLE}.client_id = 1082723 AND ${TABLE}.email_name LIKE ('ABS%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1082723 AND ${TABLE}.email_name LIKE ('CRE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('AC%') THEN 'Competition'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('Acrylic Artist 2016 Reader Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ADE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ADP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ANOE%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ANR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ANSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ANU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ARNE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ARNP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ARNS%') THEN 'Sweepstakes'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('ATV%') THEN 'TV'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('CMM%') THEN 'Editorial and Shop'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('Drawing 2016 Reader Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('DWG_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('NLS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('Pastel Journal 2016 Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('SWA%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('SWSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('TAM 2016 Ad Feedback Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('Watercolor Artist 2016 Reader Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1302102 AND ${TABLE}.email_name LIKE ('WC%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354863 AND ${TABLE}.email_name LIKE ('PI_SKY-Abandoned%') THEN 'Trigger'
            WHEN ${TABLE}.client_id = 1354863 AND ${TABLE}.email_name LIKE ('SAS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354863 AND ${TABLE}.email_name LIKE ('SKY%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354863 AND ${TABLE}.email_name LIKE ('SKY_HP_NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354863 AND ${TABLE}.email_name LIKE ('SKYSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('MTC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('MTE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('MTSO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('MTSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('OCB%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('OCE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('OCM%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('OCSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303338 AND ${TABLE}.email_name LIKE ('OCW%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303339 AND ${TABLE}.email_name LIKE ('B2B%') THEN 'B2B'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BDEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BDRE%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BDSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BDW_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BF DEB%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BSH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('BSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Call for Submissions%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Event- Bead Fest%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events - Bead Fest%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events - BeadFest DEB%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events - BeadFest NL%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events – BeadFest NL%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events - BeadFest TX PA DEB%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events – BFNL%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events Bead Fest DEB%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('Events BeadFest DEB%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372940 AND ${TABLE}.email_name LIKE ('STN_EXP%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLD%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLD Show%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLDC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLDS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303170 AND ${TABLE}.email_name LIKE ('BLS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BRSE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BRSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BRSPvideo%') THEN 'Video'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BRSSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BRSU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BSR%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1305672 AND ${TABLE}.email_name LIKE ('BSV%') THEN 'Video'
            WHEN ${TABLE}.client_id = 1324902 AND ${TABLE}.email_name LIKE ('BRUKN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1324902 AND ${TABLE}.email_name LIKE ('BRUKP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303340 AND ${TABLE}.email_name LIKE ('BESP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303340 AND ${TABLE}.email_name LIKE ('BEX%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303340 AND ${TABLE}.email_name LIKE ('Construction%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303340 AND ${TABLE}.email_name LIKE ('RESP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303340 AND ${TABLE}.email_name LIKE ('REX%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1366545 AND ${TABLE}.email_name LIKE ('CCD%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1366545 AND ${TABLE}.email_name LIKE ('CD%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372947 AND ${TABLE}.email_name LIKE ('IFA%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372947 AND ${TABLE}.email_name LIKE ('ML%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CKC%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CKO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CKP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPS Events%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPSSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CPSV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('CR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('PCSM%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('PCS-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('PCSO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354879 AND ${TABLE}.email_name LIKE ('PCSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CCFS%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CME%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CMH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CMP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CMS%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('CRZ_Expires_%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('LCC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('LCE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('LCSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354883 AND ${TABLE}.email_name LIKE ('LOC%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('Daily Heller%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DC%') THEN 'Competition'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DCF%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DSO%') THEN 'Subscription Offer'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DT%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('DTY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('HDI%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('HDLP%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('HDN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('HDOE%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('MDS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303284 AND ${TABLE}.email_name LIKE ('PRN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBA%') THEN 'Awards'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWC%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWD%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWP%') THEN 'White Paper'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBW-TY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1303341 AND ${TABLE}.email_name LIKE ('DBWU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1341728 AND ${TABLE}.email_name LIKE ('Events - GASC%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1341728 AND ${TABLE}.email_name LIKE ('GASP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTI%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTM%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTS - iGoDigital - Abandoned%') THEN 'Trigger'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTS - iGoDigital - Product Review%') THEN 'Trigger'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTTY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTUPM%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('FTU%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303281 AND ${TABLE}.email_name LIKE ('SFT%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDCE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDMS%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303168 AND ${TABLE}.email_name LIKE ('GDT%') THEN 'Trig'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('GHS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('HCC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('HCSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('HGS%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('HSG%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303171 AND ${TABLE}.email_name LIKE ('HSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JCFS%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JMDRE%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JMEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JSH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('JWA_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('TSGP%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372942 AND ${TABLE}.email_name LIKE ('Tucson Show Guide%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('AdTalk%') THEN 'Ad Sales'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('Events - Yarn Fest%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('Events- Yarn Fest Sponsor Blast%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KCFS%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KDEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KDSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KNA%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KNC_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('Knitting Daily Welcome email%') THEN 'Welcome Email'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KNS%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KNSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KSH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('KSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('LKE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('LKO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('LKSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('LOK%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('LOV%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('PWMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('PWO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354881 AND ${TABLE}.email_name LIKE ('PWP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('ATAE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('ATC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('ATE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('ATSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('GMC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('GMN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('GMSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('Goldmine 2016 Community Survey%') THEN 'Survey'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('KPS Lapsed Buyer 20%') THEN 'Automated'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('KPS New Buyer 20%') THEN 'Automated'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('KSB%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('SCD%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('SDI%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1085723 AND ${TABLE}.email_name LIKE ('SDSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1305816 AND ${TABLE}.email_name LIKE ('LRS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1305816 AND ${TABLE}.email_name LIKE ('LRSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MP%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MPEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MPIEC%') THEN 'Club'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MPS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MPSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('MPTV%') THEN 'TV'
            WHEN ${TABLE}.client_id = 1303173 AND ${TABLE}.email_name LIKE ('PI_MPS-Abandoned%') THEN 'Trigger'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NTSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('PCK_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NP% NT Sponsored%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372943 AND ${TABLE}.email_name LIKE ('NSH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NMNF%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NMNT%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NMN%') THEN 'Subscription'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NMSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NNE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('NSCC%') THEN 'Contributor'
            WHEN ${TABLE}.client_id = 1303175 AND ${TABLE}.email_name LIKE ('SNM%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('DDH%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('DDM%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('DHSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('DTN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('SDH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('THM%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('THSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('TPCSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('TPC%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('TPM%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303198 AND ${TABLE}.email_name LIKE ('TTH%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('CQC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('CQNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('CQS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FP_NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FPED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FPMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FP-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FPNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FP-NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FPPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FP-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('FP-SO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQiQ-AutoRenew%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQiQ-Renew%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQ-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('KQS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQ-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQ-NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQ-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('MCQSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QASS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCAED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCAMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCANL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCAPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCA-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QCASP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QDEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLNED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLNMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLN-MO_LC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLN-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLNNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLN-NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLNPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLN-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QLNSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMKED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMKMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMK-MO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMKNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMK-NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMKPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMK-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QMKSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QNN%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QNN_3rdParty%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QNNED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QNNNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QNNSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QP%-%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QP%_%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QSH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QTA_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QUEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QVED%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QVMO%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QVNL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QV-NL%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QVPT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QV-PT%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('QVSP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354864 AND ${TABLE}.email_name LIKE ('SFP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303367 AND ${TABLE}.email_name LIKE ('SASN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303367 AND ${TABLE}.email_name LIKE ('SASP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CME%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CME - TY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CMEC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CMEE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CMEO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('CMEP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('OSQE%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SDEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SEH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SEWEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SNC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SNE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SNO%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SNP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SWE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SWO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SWSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1354880 AND ${TABLE}.email_name LIKE ('SWP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('AdSales%') THEN 'Ad Sales'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SCFS%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SDEV%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SDEV - SOAR%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SDEV - SpinMore%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SDEV%Recommended Events%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SIO_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SPE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SPH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SPO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SPP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372945 AND ${TABLE}.email_name LIKE ('SSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303369 AND ${TABLE}.email_name LIKE ('SCCN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303369 AND ${TABLE}.email_name LIKE ('SCCP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303347 AND ${TABLE}.email_name LIKE ('THWN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('HDW_Expires%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WCFS%') THEN 'Call for Subs'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WO%') THEN 'Webinar'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1372946 AND ${TABLE}.email_name LIKE ('WTH%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('Events- WIA Exhibitor Blast%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('ICDT%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWC%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWP%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWT%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('PWV%') THEN 'Video'
            WHEN ${TABLE}.client_id = 1303174 AND ${TABLE}.email_name LIKE ('WIA%') THEN 'Events'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SMN%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SMSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SUTV%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SWC%') THEN 'Competition'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SWEV%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SWIR%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SW-TY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SWU-PM%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('SWU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('TWS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303283 AND ${TABLE}.email_name LIKE ('TWS - TY%') THEN 'TY'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('GLA%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WC%') THEN 'Competition'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDC%') THEN 'Event'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDE%') THEN 'Editorial'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDP%') THEN 'Circ'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDSP%') THEN 'DEB'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDS%') THEN 'Shop'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDT%') THEN 'Education'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WDU%') THEN 'University'
            WHEN ${TABLE}.client_id = 1303282 AND ${TABLE}.email_name LIKE ('WM%') THEN 'Editorial'
            WHEN ${TABLE}.email_name LIKE ('Ad Sales%') THEN 'Ad Sales'
            WHEN ${TABLE}.email_name LIKE ('Call for Submissions%') THEN 'Call for Subs'
            WHEN ${TABLE}.email_name LIKE ('Retailer%') THEN 'Retailer'
            WHEN ${TABLE}.email_name LIKE ('Survey Reminder%') THEN 'Survey'
            ELSE NULL END
