view: et_send_jobs {
  sql_table_name: exacttarget.main.et_send_jobs ;;
  #-- fk

  dimension: client_id {
    type: number
    sql: ${TABLE}.client_id ;;
    hidden: yes
  }

  dimension: send_id {
    label: "Send ID"
    type: number
    sql: ${TABLE}.send_id ;;
    hidden: no
  }

  #-- dimensions

  dimension: from_name {
    label: "From Name"
    type: string
    sql: ${TABLE}.from_name ;;
  }

  dimension: from_email {
    label: "From Email Adrs"
    type: string
    sql: ${TABLE}.from_email ;;
  }

  dimension: email_name {
    label: "Email Name"
    type: string
    sql: ${TABLE}.email_name ;;
  }

  dimension: subject {
    label: "Subject Line"
    type: string
    sql: ${TABLE}.subject ;;
  }

  dimension: subject_line_len {
    label: "Subject Line Length"
    type: number
    sql: length( ${TABLE}.subject ) ;;
  }

  dimension_group: sent_time {
    label: "Sent Date"
    type: time
    timeframes: [hour_of_day, day_of_week, date]
    sql: ${TABLE}.sent_time ;;
    hidden: yes
  }

  dimension: email_type {
    label: "Email Type"
    type: string
    drill_fields: [email_name]
    sql: CASE
      WHEN lower( ${TABLE}.email_name ) LIKE ('%welcome%') THEN 'Welcome Email'
      WHEN ${TABLE}.client_id = 1082723 AND lower( ${TABLE}.email_name ) LIKE lower('ABS%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1082723 AND lower( ${TABLE}.email_name ) LIKE lower('CRE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('AC%') THEN 'Competition'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('Acrylic Artist 2016 Reader Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ADE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ADP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ANOE%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ANR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ANSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ANU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ARNE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ARNP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ARNS%') THEN 'Sweepstakes'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('ATV%') THEN 'TV'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('CMM%') THEN 'Editorial and Shop'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('Drawing 2016 Reader Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('DWG_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('NLS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('Pastel Journal 2016 Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('SWA%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('SWSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('TAM 2016 Ad Feedback Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('Watercolor Artist 2016 Reader Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1302102 AND lower( ${TABLE}.email_name ) LIKE lower('WC%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354863 AND lower( ${TABLE}.email_name ) LIKE lower('PI_SKY-Abandoned%') THEN 'Trigger'
      WHEN ${TABLE}.client_id = 1354863 AND lower( ${TABLE}.email_name ) LIKE lower('SAS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354863 AND lower( ${TABLE}.email_name ) LIKE lower('SKY_HP_NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354863 AND lower( ${TABLE}.email_name ) LIKE lower('SKYSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354863 AND lower( ${TABLE}.email_name ) LIKE lower('SKY%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('MTC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('MTE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('MTSO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('MTSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('OCB%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('OCE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('OCM%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('OCSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303338 AND lower( ${TABLE}.email_name ) LIKE lower('OCW%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303339 AND lower( ${TABLE}.email_name ) LIKE lower('B2B%') THEN 'B2B'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BDEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BDRE%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BDSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BDW_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BF DEB%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BSH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('BSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Call for Submissions%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events - BeadFest DEB%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events - BeadFest NL%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events – BeadFest NL%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events - BeadFest TX PA DEB%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events – BFNL%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Event- Bead Fest%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events - Bead Fest%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events Bead Fest DEB%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('Events BeadFest DEB%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372940 AND lower( ${TABLE}.email_name ) LIKE lower('STN_EXP%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLD Show%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLDC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLDS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLD%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303170 AND lower( ${TABLE}.email_name ) LIKE lower('BLS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BRSE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BRSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BRSPvideo%') THEN 'Video'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BRSSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BRSU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BSR%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1305672 AND lower( ${TABLE}.email_name ) LIKE lower('BSV%') THEN 'Video'
      WHEN ${TABLE}.client_id = 1324902 AND lower( ${TABLE}.email_name ) LIKE lower('BRUKN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1324902 AND lower( ${TABLE}.email_name ) LIKE lower('BRUKP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303340 AND lower( ${TABLE}.email_name ) LIKE lower('BESP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303340 AND lower( ${TABLE}.email_name ) LIKE lower('BEX%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303340 AND lower( ${TABLE}.email_name ) LIKE lower('Construction%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303340 AND lower( ${TABLE}.email_name ) LIKE lower('RESP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303340 AND lower( ${TABLE}.email_name ) LIKE lower('REX%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1366545 AND lower( ${TABLE}.email_name ) LIKE lower('CCD%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1366545 AND lower( ${TABLE}.email_name ) LIKE lower('CD%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372947 AND lower( ${TABLE}.email_name ) LIKE lower('IFA%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372947 AND lower( ${TABLE}.email_name ) LIKE lower('ML%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CKC%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CKO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CKP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPS Events%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPSSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CPSV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('CR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('PCSM%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('PCS-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('PCSO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354879 AND lower( ${TABLE}.email_name ) LIKE lower('PCSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CCFS%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CME%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CMH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CMP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CMS%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('CRZ_Expires_%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('LCC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('LCE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('LCSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354883 AND lower( ${TABLE}.email_name ) LIKE lower('LOC%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('Daily Heller%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DCF%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DC%') THEN 'Competition'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DSO%') THEN 'Subscription Offer'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DTY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('DT%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('HDI%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('HDLP%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('HDN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('HDOE%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('MDS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303284 AND lower( ${TABLE}.email_name ) LIKE lower('PRN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBA%') THEN 'Awards'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWC%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWD%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWP%') THEN 'White Paper'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBW-TY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1303341 AND lower( ${TABLE}.email_name ) LIKE lower('DBWU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1341728 AND lower( ${TABLE}.email_name ) LIKE lower('Events - GASC%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1341728 AND lower( ${TABLE}.email_name ) LIKE lower('GASP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTI%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTM%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTS - iGoDigital - Abandoned%') THEN 'Trigger'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTS - iGoDigital - Product Review%') THEN 'Trigger'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTTY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTUPM%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('FTU%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303281 AND lower( ${TABLE}.email_name ) LIKE lower('SFT%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDCE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDMS%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303168 AND lower( ${TABLE}.email_name ) LIKE lower('GDT%') THEN 'Trig'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('GHS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('HCC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('HCSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('HGS%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('HSG%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303171 AND lower( ${TABLE}.email_name ) LIKE lower('HSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JCFS%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JMDRE%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JMEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JSH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('JWA_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('TSGP%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372942 AND lower( ${TABLE}.email_name ) LIKE lower('Tucson Show Guide%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('AdTalk%') THEN 'Ad Sales'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('Events - Yarn Fest%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('Events- Yarn Fest Sponsor Blast%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KCFS%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KDEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KDSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KNA%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KNC_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('Knitting Daily Welcome email%') THEN 'Welcome Email'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KNSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KNS%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KSH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('KSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('LKE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('LKO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('LKSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('LOK%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('LOV%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('PWMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('PWO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354881 AND lower( ${TABLE}.email_name ) LIKE lower('PWP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('ATAE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('ATC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('ATE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('ATSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('GMC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('GMN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('GMSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('Goldmine 2016 Community Survey%') THEN 'Survey'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('KPS Lapsed Buyer 20%') THEN 'Automated'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('KPS New Buyer 20%') THEN 'Automated'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('KSB%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('SCD%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('SDI%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1085723 AND lower( ${TABLE}.email_name ) LIKE lower('SDSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1305816 AND lower( ${TABLE}.email_name ) LIKE lower('LRSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1305816 AND lower( ${TABLE}.email_name ) LIKE lower('LRS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MPEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MPIEC%') THEN 'Club'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MPSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MPS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MPTV%') THEN 'TV'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('MP%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303173 AND lower( ${TABLE}.email_name ) LIKE lower('PI_MPS-Abandoned%') THEN 'Trigger'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NTSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('PCK_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NP% NT Sponsored%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372943 AND lower( ${TABLE}.email_name ) LIKE lower('NSH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NMNF%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NMNT%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NMN%') THEN 'Subscription'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NMSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NNSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NNE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('NSCC%') THEN 'Contributor'
      WHEN ${TABLE}.client_id = 1303175 AND lower( ${TABLE}.email_name ) LIKE lower('SNM%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('DDH%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('DDM%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('DHSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('DTN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('SDH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('THM%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('THSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('TPCSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('TPC%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('TPM%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303198 AND lower( ${TABLE}.email_name ) LIKE lower('TTH%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('CQC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('CQNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('CQS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FP_NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FPED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FPMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FP-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FPNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FP-NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FPPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FP-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('FP-SO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQiQ-AutoRenew%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQiQ-Renew%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQ-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('KQS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQ-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQ-NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQ-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('MCQSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QASS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCAED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCAMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCANL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCAPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCA-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QCASP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QDEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLNED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLNMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLN-MO_LC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLN-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLNNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLN-NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLNPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLN-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QLNSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMKED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMKMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMK-MO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMKNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMK-NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMKPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMK-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QMKSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QNN_3rdParty%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QNNED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QNNNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QNNSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QNN%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QP%-%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QP%_%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QSH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QTA_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QUEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QVED%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QVMO%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QVNL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QV-NL%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QVPT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QV-PT%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('QVSP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354864 AND lower( ${TABLE}.email_name ) LIKE lower('SFP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303367 AND lower( ${TABLE}.email_name ) LIKE lower('SASN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303367 AND lower( ${TABLE}.email_name ) LIKE lower('SASP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CME - TY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CMEC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CMEE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CMEO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CMEP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('CME%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('OSQE%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SDEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SEH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SEWEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SNC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SNE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SNO%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SNP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SWE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SWO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SWSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1354880 AND lower( ${TABLE}.email_name ) LIKE lower('SWP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('AdSales%') THEN 'Ad Sales'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SCFS%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SDEV - SOAR%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SDEV - SpinMore%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SDEV%Recommended Events%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SDEV%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SIO_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SPE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SPH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SPO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SPP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372945 AND lower( ${TABLE}.email_name ) LIKE lower('SSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303369 AND lower( ${TABLE}.email_name ) LIKE lower('SCCN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303369 AND lower( ${TABLE}.email_name ) LIKE lower('SCCP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303347 AND lower( ${TABLE}.email_name ) LIKE lower('THWN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('HDW_Expires%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WCFS%') THEN 'Call for Subs'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WO%') THEN 'Webinar'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1372946 AND lower( ${TABLE}.email_name ) LIKE lower('WTH%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('Events- WIA Exhibitor Blast%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('ICDT%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWC%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWP%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWT%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('PWV%') THEN 'Video'
      WHEN ${TABLE}.client_id = 1303174 AND lower( ${TABLE}.email_name ) LIKE lower('WIA%') THEN 'Events'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SMN%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SMSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SUTV%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SWC%') THEN 'Competition'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SWEV%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SWIR%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SW-TY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SWU-PM%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('SWU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('TWS - TY%') THEN 'TY'
      WHEN ${TABLE}.client_id = 1303283 AND lower( ${TABLE}.email_name ) LIKE lower('TWS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('GLA%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WC%') THEN 'Competition'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDC%') THEN 'Event'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDE%') THEN 'Editorial'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDP%') THEN 'Circ'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDSP%') THEN 'DEB'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDS%') THEN 'Shop'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDT%') THEN 'Education'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WDU%') THEN 'University'
      WHEN ${TABLE}.client_id = 1303282 AND lower( ${TABLE}.email_name ) LIKE lower('WM%') THEN 'Editorial'
      WHEN lower( ${TABLE}.email_name ) LIKE lower('Ad Sales%') THEN 'Ad Sales'
      WHEN lower( ${TABLE}.email_name ) LIKE lower('Call for Submissions%') THEN 'Call for Subs'
      WHEN lower( ${TABLE}.email_name ) LIKE lower('Retailer%') THEN 'Retailer'
      WHEN lower( ${TABLE}.email_name ) LIKE lower('Survey Reminder%') THEN 'Survey'
      ELSE NULL END
 ;;
  }
}
